// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNTgkdWhMiX4_9Xfb7YSdoZB2Xckk9N_8',
    appId: '1:427911948085:web:49e31d73fcb8cd6e550e7c',
    messagingSenderId: '427911948085',
    projectId: 'softwarelabs-10ce2',
    authDomain: 'softwarelabs-10ce2.firebaseapp.com',
    storageBucket: 'softwarelabs-10ce2.appspot.com',
    measurementId: 'G-HCLDV6HZBB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQAk1LYomLpsfz4WuxkfaZtFSrlCHvD64',
    appId: '1:427911948085:android:7db4aba6056132d3550e7c',
    messagingSenderId: '427911948085',
    projectId: 'softwarelabs-10ce2',
    storageBucket: 'softwarelabs-10ce2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUMmdGdwWVtR3GFaTr_6VoplDzKAKvmDk',
    appId: '1:427911948085:ios:6253ef6c05e57842550e7c',
    messagingSenderId: '427911948085',
    projectId: 'softwarelabs-10ce2',
    storageBucket: 'softwarelabs-10ce2.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUMmdGdwWVtR3GFaTr_6VoplDzKAKvmDk',
    appId: '1:427911948085:ios:6253ef6c05e57842550e7c',
    messagingSenderId: '427911948085',
    projectId: 'softwarelabs-10ce2',
    storageBucket: 'softwarelabs-10ce2.appspot.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNTgkdWhMiX4_9Xfb7YSdoZB2Xckk9N_8',
    appId: '1:427911948085:web:57db0bd3ad78d2fd550e7c',
    messagingSenderId: '427911948085',
    projectId: 'softwarelabs-10ce2',
    authDomain: 'softwarelabs-10ce2.firebaseapp.com',
    storageBucket: 'softwarelabs-10ce2.appspot.com',
    measurementId: 'G-M1W2F19XYR',
  );

}